### PR TITLE
Add structured logging, context data

### PR DESCRIPTION
**Pull request by mephinet**
This pull request adds three features to Log::Any, as proposed in http://blogs.perl.org/users/mephinet/2017/02/log-any-adventures.html: 

 1.  it extends the API between applications and Log::Any::Adapters to allow passing hashrefs in addition to a plain string
 1.  it allows applications to specify (possibly localized) context data for Log::Any to add to each log message
 1.  it allows system owners to globally specify a default adapter other than Null

The changes are fully backwards-compatible, and I've tried to minimize runtime overhead. In short, adapters can now implement a `structured` method instead of `warn`, `error`, `info`, etc. If they do, they will receive all arguments given to the log method, including hashrefs, without them being flattened to a string by the proxy. This allows the adapter to process the data without having to re-evaluate the string it receives.
On top of this, $log now exposes as `context` hash, where applications can add (localized) data that will be added to each log message. For non-structured adapters, the context will by Data::Dumper'ed and appended to the log line, as one would expect, whereas structured adapters will receive the unaltered hash.
The pull request also contains unittests for the new features, and the necessary documentation changes for Log::Any users and adapter developers.

To give this module a try, you can use https://github.com/mephinet/perl-Log-Any-Adapter-Screen/blob/structured-logging/lib/Log/Any/Adapter/Screen.pm as an adapter and https://gist.github.com/mephinet/c1e48e0a6d6bbd5949483e24aeac9961 as a sample application.

Please let me know what you think of these proposed changes!

### CODE REVIEW

**Comment by preaction** [comment]
Thanks for doing all this work. This is a good idea, and I want to have structured logging in Log::Any (akin to Log::Log4perl's Mapped Diagnostic Context), but there are some changes that should be made:

1. Some of these commits change a lot of whitespace and other things unrelated to the commit's stated purpose. Please separate these changes out into other commits, one for each purpose. I would prefer you not mess with the existing code's whitespace, but the POD links you added are a good idea. You also don't need to mention there's a unit test in the commit message: all commits that need them must have them.

2. Do not commit the generated files like `README.mkdn`, `cpanfile`, and `Makefile.PL`. These are rebuilt at release time. Adding the changes to those files makes it harder to see what changed in the commit.

As for the features you've added:

The `context` hash you added seems to be on a per-Proxy level. This makes it less useful than I'd like, and the change to make it global/scoped (#46) would be a breaking change if this got released as-is. The use-case I see for contextual logging is more akin to:

```perl
# Test that two loggers in the call stack share the same context
Log::Any::Adapter->set('+TestAdapters::Normal');

# Controller sets information about the current http request
my $log = Log::Any->get_logger( category => 'MyApp::Controller' );
local $log->context->{http_method} = 'GET';
local $log->context->{http_path} = '/foo/bar/baz';
local $log->context->{request_id} = int( rand * time );

sub model {
    # Model writes to the log, but we need to know which http request we're handling...
    my $log2 = Log::Any->get_logger( category => 'MyApp::Model' );
    $log2->info( "some info" );
}
model();

like( $TestAdapters::TEXT_LOG[0], qr{some info {http_method => "GET",http_path => "/foo/bar/baz",request_id => \d+}} );
```

Since our model layer (or some other distribution on CPAN) gets its own log proxy, the context needs to be a global state. My ideal solution would be a combination of Log4perl's Nested Diagnostic Context (which only allows simple string identifiers, not hash references) and Mapped Diagnostic Contexts (which is a hash, but is not organized in a stack for easy unwinding of values). In theory we could get far with `local $log->context->{foo} = "bar"`, provided that `$log->context` was a global hashref in `Log::Any::Manager`, but I'm open to ways to make it less cumbersome to update multiple values:

```perl
# One line for each value is not ideal
local $log->context->{http_method} = 'GET';
local $log->context->{http_path} = '/foo/bar/baz';
local $log->context->{request_id} = int( rand * time );

# This syntax just kind of looks weird
local %{ $log->context } = (
    %{ $log->context },
    http_method => 'GET',
    http_path => '/foo/bar/baz',
    request_id => int( rand * time ),
);

# 5.24 postderef makes this easier
use v5.24;
local $log->context->%* = (
    $log->context->%*,
    http_method => 'GET',
    http_path => '/foo/bar/baz',
    request_id => int( rand * time ),
);
# ... or ...
local $log->context->@{qw( http_method http_path request_id )} = ( 'GET', '/foo/bar/baz', int( rand * time ) );

# ... but this is unfortunately a syntax error
local $log->context->%{qw( http_method http_path request_id )} = (
    http_method => 'GET',
    http_path => '/foo/bar/baz',
    request_id => int( rand * time ),
);
```

We could add better API methods for dealing with context scoping in a later patch.

I would also really prefer that the structured logging be restricted to a single, unblessed hashref as the last argument to the logging method. Users can put anything inside that hashref, but it must be a hashref. The rest just gets stringified as is currently the case. This will simplify how adapters deal with the structured bits. Also, if `$log->context` is a hashref, the structured logging must always be a hashref in order for the context to work together with structures passed to the method.

The new behavior of references in log proxies is a breaking change, and we need to do everything in our power to minimize the hassle. Restricting it to a single, unblessed hashref in the last argument will help. I can write some tests to demonstrate if you'd like, then you'd just have to make the tests pass.

To my knowledge, the only adapter that could take full advantage of this is Log4perl. Custom adapters can do anything, of course, but the goal of this project is for swapping adapters to not largely change the production/consumption of logs, so there's some amount of reduction to the lowest common set of features that needs to be done by Log-Any (adapters should be simple). That said, I think structured and scoped logging are super-important, so adding some support for both that adapters (and the underlying system) can grow to use is a good idea.

If you want to get the `LOG_ANY_DEFAULT_ADAPTER` environment variable merged first, you can split it out into another PR. That's good to go.

**Comment by mephinet** [comment]
I'm glad that you're in favor of doing these changes, Doug!
 - re tidyall changes and generated files: I think the best way to perform these changes now is to create a new branch, rebase and fixup the commits there, and create a new pull request - right?
 - re making context hash global: oh, absolutely, thanks for pointing that out! As I haven't used more than one proxy so far, I didn't think of this. I'll improve the commits to that extent...
 - re only one hashref: yeah, that's probably a good restriction, I can't think of a use-case where several hashes would make sense...

It'll take a few weeks :-)

**Comment by preaction** [comment]
You can fix this branch as it is (using `rebase -i` and `commit --amend` and etc... rewriting history) and then `push -f` and then I'll (I think) get notified of the changes (so you shouldn't have to close this PR and re-open it, which should then let the conversation be followable for future research into these features).

**Comment by mephinet** [comment]
I've tried to improve my pull request (by rebasing, and two additional commits):
- the whitespace changes are gone. I completely refrained from using perltidy or tidyall, even though the contributing guidelines advise to - if you want me to run them on a per-commit-basis or in a final cleanup commit, please let me know 
- generated files are no longer part of the commits
- the `context` hash is now stored by the manager and shared between all proxies
- documentation is now clear that we're talking about a single hashref, and only a single unblessed hashref is stringified by the proxy. However, I don't perform any strict type checking apart from that (as it might break existing non-conforming code)

Hope that meets your expectations...

**Comment by preaction** [comment]
This looks great, thanks!

I'm sorry about the contributing doc mentioning tidyall/perltidy. That's from when it was David's project. Like everyone, I've got my own ideas around that... I'll fix that before I send off this PR in a dev release.

If you don't mind, I'm going to add a couple tests for some edge cases I just thought of:

* I want to test localizing the context keys, to make sure that feature stays working. I think contextual logging is super-important
* What should happen if structured logging is used with context? Right now, it seems the one is added after the other. Is that what we (and other users) want? Would it be more useful to combine the structure with the context? Is it worth it?

I'm of the opinion that we release this as-is as a dev release and announce it so people will test and give feedback, but I'm skeptical that we'll actually get any...

**Comment by preaction** [comment]
Okay, I've merged this in to master and will release a trial release and post a blog post asking people to try it out and asking the question about structured logging + contextual logging. Thanks for all the help!

**Comment by mephinet** [comment]
Great, thanks! I'll give a short talk next week at the Perl Conference in Amsterdam, so the timing of the trial release is perfect...

**Pull request closed without merging**
